2024-03-15T10:17:25 {"cpu": 0.6416015625, "cpu_total": 2, "cpu_usage": 0.32080078125, "memory": 2742.0, "memory_total": 7929.0, "memory_usage": 0.3458191449110859, "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 7 in schedule 2 is alive.", "timestamp": 1710497845.519041, "uuid": "e9fa8ddf288f4b8ba02e05d905ee7100"}
2024-03-15T10:17:25 {"block_run_id": 73, "block_uuid": "load_customer_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 73: pipeline export_to_big_query block load_customer_dimension", "timestamp": 1710497845.78888, "uuid": "9cfd466b890d44018d612dcb070208d0"}
2024-03-15T10:17:26 {"cpu": 0.6416015625, "cpu_total": 2, "cpu_usage": 0.32080078125, "memory": 2801.0, "memory_total": 7929.0, "memory_usage": 0.35326018413419097, "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 7 in schedule 2 is alive.", "timestamp": 1710497846.173837, "uuid": "1222e878015541dc84d3fa9e11da1c3d"}
2024-03-15T10:17:26 {"block_run_id": 75, "block_uuid": "load_department_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 75: pipeline export_to_big_query block load_department_dimension", "timestamp": 1710497846.874913, "uuid": "2c1517ea7c6940418afb9d9eb941631c"}
2024-03-15T10:17:26 {"block_run_id": 80, "block_uuid": "load_metadata_dimensio", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 80: pipeline export_to_big_query block load_metadata_dimensio", "timestamp": 1710497846.928505, "uuid": "ef0b543fe5be495e8a60bfcf631d9dc5"}
2024-03-15T10:17:26 {"block_run_id": 81, "block_uuid": "load_order_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 81: pipeline export_to_big_query block load_order_dimension", "timestamp": 1710497846.998529, "uuid": "bc492f369eba4ce0a7bc4b8a365170ed"}
2024-03-15T10:17:27 {"block_run_id": 85, "block_uuid": "load_shipping_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 85: pipeline export_to_big_query block load_shipping_dimension", "timestamp": 1710497847.096692, "uuid": "08113172b3964ed9bd68cb1cd7011679"}
2024-03-15T10:17:27 {"block_run_id": 83, "block_uuid": "load_product_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 83: pipeline export_to_big_query block load_product_dimension", "timestamp": 1710497847.160253, "uuid": "b747de519ac04ee283a5129fb9ff1249"}
2024-03-15T10:17:27 {"block_run_id": 77, "block_uuid": "load_location_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 77: pipeline export_to_big_query block load_location_dimension", "timestamp": 1710497847.211248, "uuid": "827171c126ff41e5bddb21fb263c5ad4"}
2024-03-15T10:17:32 {"block_run_id": 75, "block_uuid": "load_department_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 75 (block_uuid: load_department_dimension) completes.", "timestamp": 1710497852.36313, "uuid": "d8480e1c26dd4993bc94cbd3c978a500"}
2024-03-15T10:17:34 {"block_run_id": 73, "block_uuid": "load_customer_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 73 (block_uuid: load_customer_dimension) completes.", "timestamp": 1710497854.741888, "uuid": "36f20fe76ebd4149ace131e4edbdbd08"}
2024-03-15T10:17:35 {"block_run_id": 85, "block_uuid": "load_shipping_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 85 (block_uuid: load_shipping_dimension) completes.", "timestamp": 1710497855.180829, "uuid": "4262cca54f564a9aaadfa6dac57c04d1"}
2024-03-15T10:17:35 {"cpu": 0.65087890625, "cpu_total": 2, "cpu_usage": 0.325439453125, "memory": 3446.0, "memory_total": 7929.0, "memory_usage": 0.43460713835288184, "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 7 in schedule 2 is alive.", "timestamp": 1710497855.494415, "uuid": "7b7c2abbac004bc9a300c2be03b0c90a"}
2024-03-15T10:17:35 {"block_run_id": 83, "block_uuid": "load_product_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 83 (block_uuid: load_product_dimension) completes.", "timestamp": 1710497855.914704, "uuid": "2086a95024fc4795bb3c077081f327a7"}
2024-03-15T10:17:36 {"block_run_id": 80, "block_uuid": "load_metadata_dimensio", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 80 (block_uuid: load_metadata_dimensio) completes.", "timestamp": 1710497856.337203, "uuid": "32b462be486b415d9b0890289f6bc5cf"}
2024-03-15T10:17:36 {"block_run_id": 74, "block_uuid": "customer_dim_to_big_query", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 74: pipeline export_to_big_query block customer_dim_to_big_query", "timestamp": 1710497856.348753, "uuid": "fcf4fe16f3d54f7eb476f3242282e089"}
2024-03-15T10:17:37 {"block_run_id": 77, "block_uuid": "load_location_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 77 (block_uuid: load_location_dimension) completes.", "timestamp": 1710497857.018294, "uuid": "d3200332f6e7493b9bd5e7fd1777481c"}
2024-03-15T10:17:37 {"block_run_id": 76, "block_uuid": "department_dim_to_big_query", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 76: pipeline export_to_big_query block department_dim_to_big_query", "timestamp": 1710497857.212922, "uuid": "0fbb492cbad84c29815941c621511606"}
2024-03-15T10:17:37 {"block_run_id": 86, "block_uuid": "shipping_dim_to_big_query", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 7, BlockRun 86: pipeline export_to_big_query block shipping_dim_to_big_query", "timestamp": 1710497857.259808, "uuid": "8b79262a8973433a9016a62c9494b80c"}
2024-03-15T10:17:39 {"block_run_id": 81, "block_uuid": "load_order_dimension", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 81 (block_uuid: load_order_dimension) completes.", "timestamp": 1710497859.607915, "uuid": "8a3a63f06fa64a9486baf7e333289252"}
2024-03-15T10:17:43 {"block_run_id": 86, "block_uuid": "shipping_dim_to_big_query", "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "EXCEPTION", "message": "BlockRun 86 (block_uuid: shipping_dim_to_big_query) failed.", "timestamp": 1710497863.870527, "uuid": "0594eeab817340dbb22c81b6d623978a", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2491, in load_table_from_file\n    response = self._do_multipart_upload(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 3046, in _do_multipart_upload\n    response = upload.transmit(\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py\", line 153, in transmit\n    return _request_helpers.wait_and_retry(\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py\", line 155, in wait_and_retry\n    response = func()\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py\", line 149, in retriable_request\n    self._process_response(result)\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/_upload.py\", line 125, in _process_response\n    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/_helpers.py\", line 108, in require_status_code\n    raise common.InvalidResponse(\ngoogle.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1315, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1224, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1530, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1686, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1725, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 319, in export\n    __process(database=database)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 315, in __process\n    self.client.load_table_from_dataframe(df, table_id, job_config=config).result()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2727, in load_table_from_dataframe\n    return self.load_table_from_file(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2495, in load_table_from_file\n    raise exceptions.from_http_response(exc.response)\ngoogle.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name \"Days_for_shipment_(scheduled)\". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1615, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 190, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 602, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1152, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 433, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name \"Days_for_shipment_(scheduled)\". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2491, in load_table_from_file
    response = self._do_multipart_upload(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 3046, in _do_multipart_upload
    response = upload.transmit(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
    self._process_response(result)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_upload.py", line 125, in _process_response
    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1315, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1224, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1530, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1686, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1725, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 319, in export
    __process(database=database)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 315, in __process
    self.client.load_table_from_dataframe(df, table_id, job_config=config).result()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2727, in load_table_from_dataframe
    return self.load_table_from_file(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2495, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name "Days_for_shipment_(scheduled)". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names
2024-03-15T10:17:45 {"cpu": 0.67041015625, "cpu_total": 2, "cpu_usage": 0.335205078125, "memory": 3159.0, "memory_total": 7929.0, "memory_usage": 0.39841089670828606, "pipeline_run_id": 7, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 7 in schedule 2 is alive.", "timestamp": 1710497865.368776, "uuid": "cbcbaf972b724f9c9fd4cee05a3604cd"}
