2024-03-15T07:16:39 {"cpu": 0.357421875, "cpu_total": 2, "cpu_usage": 0.1787109375, "memory": 2664.0, "memory_total": 7929.0, "memory_usage": 0.33598183881952326, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Pipeline radiant_spell for run 2 in schedule 1 is alive.", "timestamp": 1710486999.029988, "uuid": "d49e136bec12434db44d5443d81dd42d"}
2024-03-15T07:16:39 {"block_run_id": 3, "block_uuid": "load_customer_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 3: pipeline radiant_spell block load_customer_dimension", "timestamp": 1710486999.360622, "uuid": "c503b4548c0f4e7c916b58092f80c22e"}
2024-03-15T07:16:39 {"cpu": 0.37744140625, "cpu_total": 2, "cpu_usage": 0.188720703125, "memory": 2704.0, "memory_total": 7929.0, "memory_usage": 0.34102661117417077, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Pipeline radiant_spell for run 2 in schedule 1 is alive.", "timestamp": 1710486999.795632, "uuid": "10e81fc94a0b4af5920042278e3517aa"}
2024-03-15T07:16:40 {"block_run_id": 5, "block_uuid": "load_department_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 5: pipeline radiant_spell block load_department_dimension", "timestamp": 1710487000.418281, "uuid": "1c59085874034295adcabe0a41b933ca"}
2024-03-15T07:16:40 {"block_run_id": 7, "block_uuid": "load_location_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 7: pipeline radiant_spell block load_location_dimension", "timestamp": 1710487000.512146, "uuid": "96fa183342e34286909c74a52f7f505c"}
2024-03-15T07:16:40 {"block_run_id": 10, "block_uuid": "load_metadata_dimensio", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 10: pipeline radiant_spell block load_metadata_dimensio", "timestamp": 1710487000.702652, "uuid": "9b29a2d6ad8748129b9034fe3207afb0"}
2024-03-15T07:16:40 {"block_run_id": 13, "block_uuid": "load_product_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 13: pipeline radiant_spell block load_product_dimension", "timestamp": 1710487000.703865, "uuid": "e11b0101e4c84496bd8e99b625021fab"}
2024-03-15T07:16:40 {"block_run_id": 15, "block_uuid": "load_shipping_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 15: pipeline radiant_spell block load_shipping_dimension", "timestamp": 1710487000.717995, "uuid": "4cc7496d718e4505ac68b5f5d3ba3d48"}
2024-03-15T07:16:40 {"block_run_id": 11, "block_uuid": "load_order_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 11: pipeline radiant_spell block load_order_dimension", "timestamp": 1710487000.933598, "uuid": "98f1cee50a1e4fe78761ae30bcf501e5"}
2024-03-15T07:16:46 {"block_run_id": 5, "block_uuid": "load_department_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "BlockRun 5 (block_uuid: load_department_dimension) completes.", "timestamp": 1710487006.003012, "uuid": "d52f761c109c4743aa5995ee1dbdcda9"}
2024-03-15T07:16:48 {"block_run_id": 13, "block_uuid": "load_product_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "BlockRun 13 (block_uuid: load_product_dimension) completes.", "timestamp": 1710487008.987504, "uuid": "899ce47063ad4bd89e135bc94594088b"}
2024-03-15T07:16:49 {"block_run_id": 15, "block_uuid": "load_shipping_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "BlockRun 15 (block_uuid: load_shipping_dimension) completes.", "timestamp": 1710487009.42343, "uuid": "e79225def8b34aa7898133427ae84097"}
2024-03-15T07:16:49 {"cpu": 0.375, "cpu_total": 2, "cpu_usage": 0.1875, "memory": 3353.0, "memory_total": 7929.0, "memory_usage": 0.4228780426283264, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Pipeline radiant_spell for run 2 in schedule 1 is alive.", "timestamp": 1710487009.444686, "uuid": "534dc1d5997740d7a5028fa6ece2ce3e"}
2024-03-15T07:16:49 {"block_run_id": 10, "block_uuid": "load_metadata_dimensio", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "BlockRun 10 (block_uuid: load_metadata_dimensio) completes.", "timestamp": 1710487009.944064, "uuid": "19bf4a1df3d4436ca26517e998a016d7"}
2024-03-15T07:16:50 {"block_run_id": 16, "block_uuid": "shipping_dim_to_big_query", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 16: pipeline radiant_spell block shipping_dim_to_big_query", "timestamp": 1710487010.726652, "uuid": "cfd39f74f88843ea8272e20874204af5"}
2024-03-15T07:16:50 {"block_run_id": 6, "block_uuid": "department_dim_to_big_query", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 6: pipeline radiant_spell block department_dim_to_big_query", "timestamp": 1710487010.740083, "uuid": "db1afa28c8e1499ab804d478ae243846"}
2024-03-15T07:16:50 {"block_run_id": 14, "block_uuid": "product_dim_to_big_query", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 14: pipeline radiant_spell block product_dim_to_big_query", "timestamp": 1710487010.974323, "uuid": "abe0329e06864b87887c312b7f95552e"}
2024-03-15T07:16:51 {"block_run_id": 7, "block_uuid": "load_location_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "BlockRun 7 (block_uuid: load_location_dimension) completes.", "timestamp": 1710487011.238751, "uuid": "36f70d22a2c746bb86aa2a237f3c24c3"}
2024-03-15T07:16:51 {"block_run_id": 11, "block_uuid": "load_order_dimension", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "BlockRun 11 (block_uuid: load_order_dimension) completes.", "timestamp": 1710487011.892565, "uuid": "20094b65bef440b1be4999e46f3a2212"}
2024-03-15T07:16:58 {"block_run_id": 16, "block_uuid": "shipping_dim_to_big_query", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "EXCEPTION", "message": "BlockRun 16 (block_uuid: shipping_dim_to_big_query) failed.", "timestamp": 1710487018.50065, "uuid": "2310c2064edf4f0ba386fa820df6d7f1", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2491, in load_table_from_file\n    response = self._do_multipart_upload(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 3046, in _do_multipart_upload\n    response = upload.transmit(\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py\", line 153, in transmit\n    return _request_helpers.wait_and_retry(\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py\", line 155, in wait_and_retry\n    response = func()\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py\", line 149, in retriable_request\n    self._process_response(result)\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/_upload.py\", line 125, in _process_response\n    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/_helpers.py\", line 108, in require_status_code\n    raise common.InvalidResponse(\ngoogle.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1315, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1224, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1530, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1686, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1725, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 319, in export\n    __process(database=database)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 315, in __process\n    self.client.load_table_from_dataframe(df, table_id, job_config=config).result()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2727, in load_table_from_dataframe\n    return self.load_table_from_file(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2495, in load_table_from_file\n    raise exceptions.from_http_response(exc.response)\ngoogle.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name \"Shipping_date_(DateOrders)\". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1615, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 190, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 602, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1152, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 433, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name \"Shipping_date_(DateOrders)\". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2491, in load_table_from_file
    response = self._do_multipart_upload(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 3046, in _do_multipart_upload
    response = upload.transmit(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
    self._process_response(result)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_upload.py", line 125, in _process_response
    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1315, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1224, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1530, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1686, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1725, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 319, in export
    __process(database=database)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 315, in __process
    self.client.load_table_from_dataframe(df, table_id, job_config=config).result()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2727, in load_table_from_dataframe
    return self.load_table_from_file(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2495, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name "Shipping_date_(DateOrders)". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names
2024-03-15T07:16:58 {"cpu": 0.40283203125, "cpu_total": 2, "cpu_usage": 0.201416015625, "memory": 3208.0, "memory_total": 7929.0, "memory_usage": 0.4045907428427292, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "radiant_spell", "hostname": "206c8e5e6755", "level": "INFO", "message": "Pipeline radiant_spell for run 2 in schedule 1 is alive.", "timestamp": 1710487018.646347, "uuid": "c4d536228c4944b19dc884e3887adbcf"}
